name: napari
channels:
  - conda-forge
  # - manics
dependencies:
  - jupyter-server-proxy
  - python=3.8
  - pip
  - dask
  - numcodecs
  - scikit-image
  - numpy
  - scipy
  - matplotlib-base
  - pip:
    - websockify==0.9.0
    - napari
    - tifffile[all]
