name: napari
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip:
    - jupyter-server-proxy
    - numpy
    - websockify==0.9.0
    - napari
    - scikit-image
    - tifffile[all]
